site:
  title: Maarif Haque - UI/UX Designer
  description: UI/UX Designer specializing in user-centered design and digital experiences
  author: Maarif Haque
  email: reachmaarif@gmail.com

  navigationMain:
    - label: Work
      href: /
    - label: About
      href: /about
    - label: CV
      href: /cv

  socialLinkedinUrl: https://linkedin.com/in/@maarifhaque
  socialEmailAddress: reachmaarif@gmail.com
  